---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: web-route-config
spec:
  routes:
  - predicates:
    - Path=/**
    - Method=GET
    order: 1000
    filters:
    - StripPrefix=0
    tags:
    - ui
  service:
    name: peekaboo

---

apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: web-route-mapping
spec:
  gatewayRef:
    name: spring-cloud-gateway
  routeConfigRef:
    name: web-route-config

--- 
