trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: GCR-US
        repository: $(imageRepository)/$(containerName)
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: drop
        publishLocation: Container

