apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: clientcapture
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: clientcapture
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
      autoscaling.knative.dev/max-scale: "50"
      autoscaling.knative.dev/scale-down-delay: "3s"
  source:
    git:
      url: https://github.com/davlloyd/clientcapture-python
      ref:
        branch: main
