apiVersion: v1
kind: Service
metadata:
  name: webreporter
  labels:
    app: webreporter
spec:
  ports:
    - port: 80
  selector:
    app: webreporter
  sessionAffinity: ClientIP
  type: LoadBalancer
  loadBalancerIP: 172.16.1.222


