---
apiVersion: v1
kind: Secret
metadata:
  name: clientcapture-db
type: servicebinding.io/mysql
stringData:
  type: mysql
  provider: mariadb
  host: clientcapture-db
  port: "3306"
  database: clientcapture
  # demo credentials
  username: user
  password: pass
  
  
---
apiVersion: v1
kind: Service
metadata:
  name: clientcapture-db
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: clientcapture-db
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientcapture-db
  labels:
    app: clientcapture-db
spec:
  selector:
    matchLabels:
      app: clientcapture-db
  template:
    metadata:
      labels:
        app: clientcapture-db
    spec:
      # no persistance configured, the database will be reset when the pod terminates
      containers:
      - image: mariadb:10.5
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: clientcapture-db
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clientcapture-db
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: clientcapture-db
              key: database
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          tcpSocket:
            port: mysql
        readinessProbe:
          tcpSocket:
            port: mysql
        startupProbe:
          tcpSocket:
            port: mysql