---
apiVersion: v1
kind: Secret
metadata:
  name: peekaboo-db
type: servicebinding.io/mysql
stringData:
  type: mysql
  provider: mariadb
  host: peekaboo-db
  port: "3306"
  database: peekaboo
  username: someuser
  password: setdbpasswordhere
  
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peekaboo-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
 
---
apiVersion: v1
kind: Service
metadata:
  name: peekaboo-db
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: peekaboo-db
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekaboo-db
  labels:
    app: peekaboo-db
spec:
  selector:
    matchLabels:
      app: peekaboo-db
  template:
    metadata:
      labels:
        app: peekaboo-db
    spec:
      containers:
      - image: mariadb:10.5
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: peekaboo-db
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peekaboo-db
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: peekaboo-db
              key: database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peekaboo-db
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          tcpSocket:
            port: mysql
        readinessProbe:
          tcpSocket:
            port: mysql
        startupProbe:
          tcpSocket:
            port: mysql
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: peekaboo-db-data
